import { Tasks } from "../models/task"

export const taskList: Tasks[] = [
	{
		_id: "1",
		categoryId: "1",
		creatorId: "1",
		name: "FWEB Part 2",
		dueDate: "2022-07-17T23:59:00",
		priority: "High",
		isCompleted: false,
		subTask: [
			{
				_id: "1",
				creatorId: "1",
				name: "something about why react is better",
				dueDate: "2022-07-17T23:59:00",
				priority: "High",
				isCompleted: true,
			},
			{
				_id: "2",
				creatorId: "1",

				name: "idk man something about angular being bad",
				dueDate: "2022-07-17T23:59:00",
				priority: "High",
				isCompleted: false,
			},
		],
	},
	{
		_id: "2",
		categoryId: "2",
		creatorId: "1",
		name: "MBAP Part 2",
		dueDate: "2022-06-29T23:59:00",
		priority: "High",
		isCompleted: false,
		subTask: [
			{
				_id: "1",
				creatorId: "1",
				name: "something about why flutter is amazing",
				dueDate: "2022-07-16T23:59:00",
				priority: "Medium",
				isCompleted: false,
			},
			{
				_id: "2",
				creatorId: "1",

				name: "something about us having to make a widget tree",
				dueDate: "2022-07-19T23:59:00",
				priority: "Low",
				isCompleted: false,
			},
			{
				_id: "3",
				creatorId: "1",
				name: "something else I guess",
				dueDate: "2022-08-19T23:59:00",
				priority: "Low",
				isCompleted: false,
			},
		],
	},
	{
		_id: "3",
		categoryId: "2",
		creatorId: "1",
		name: "MBAP Part 3",
		dueDate: "2022-08-05T23:59:00",
		priority: "High",
		isCompleted: false,
		subTask: [],
	},
	{
		_id: "4",
		categoryId: "4",
		creatorId: "1",
		name: "Innova BMC Quiz",
		dueDate: "2022-08-05T23:59:00",
		priority: "High",
		isCompleted: false,
		subTask: [
			{
				_id: "1",
				creatorId: "2",
				name: "Study for quiz",
				dueDate: "2022-07-17T23:59:00",
				priority: "Medium",
				isCompleted: false,
			},
			{
				_id: "2",
				creatorId: "2",
				name: "Study for quiz",
				dueDate: "2022-07-31T23:59:00",
				priority: "Medium",
				isCompleted: false,
			},
		],
	},
]
